sql:
  # 1 / sample_rateで処方が無いデータをサンプリングする
  sample_rate: 5
  sum_days: ${preprocess.sql.sum_days}
  train_days: ${preprocess.sql.train_days}
  valid_days: ${preprocess.sql.valid_days}
  test_days: ${preprocess.sql.test_days}

trainer:
  debug: False
  gcp_project: ${env.gcp_project}
  dataset: train_dataset
  bucket: ${env.train_bucket}
  model_path: ${execution_date}/model
  importance_path: ${execution_date}/feature_importance
  evaluation_path: ${execution_date}/evaluation_result
  latest_model_path: latest/model
  lgbm:
    numerical_cols: ${feature.numerical_cols}
    cat_cols: ${feature.cat_cols}
    label_col: ${feature.label_col}
    early_stopping_rounds: 200
    verbose_eval: 100
    num_iterations: 100000
    params:
      lambda_l1: 0.1
      lambda_l2: 0.1
      num_leaves: 32
      feature_fraction: 0.5
      bagging_fraction: 0.5
      bagging_freq: 1
      min_child_samples: 10
      task: train
      boosting_type: gbdt
      objective: rmse
      metric: rmse
      max_depth: 8
      learning_rate: 0.01
      num_thread: -1
      max_bin: 256
      verbose: -1
      device: cpu
      scale_pos_weight: 1
      seed: 777
